In [ ]:
#参考文章
#https://blog.csdn.net/ndhtou222/article/details/106416802/

In [3]:
import akshare as ak
#获取查看指数列表
index_stock_info_df = ak.index_stock_info()
index_stock_info_df

    index_code display_name publish_date
0       000001         上证指数   1991-07-15
1       000002         A股指数   1992-02-21
2       000003         B股指数   1992-02-21
3       000004         工业指数   1993-05-03
4       000005         商业指数   1993-05-03
..         ...          ...          ...
714     399994   中证信息安全主题指数   2015-03-12
715     399995     中证基建工程指数   2015-03-12
716     399996     中证智能家居指数   2014-09-17
717     399997       中证白酒指数   2015-01-21
718     399998       中证煤炭指数   2015-02-13

[719 rows x 3 columns]

In [4]:
import akshare as ak
#获取查看指数成分
index_stock_cons_df = ak.index_stock_cons(symbol="000300")
index_stock_cons_df

c:\Users\huzhe\.conda\envs\py310\lib\site-packages\akshare\index\index_cons.py:109: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  [temp_df, pd.read_html(r.text, header=1)[3]], ignore_index=True
c:\Users\huzhe\.conda\envs\py310\lib\site-packages\akshare\index\index_cons.py:109: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  [temp_df, pd.read_html(r.text, header=1)[3]], ignore_index=True
c:\Users\huzhe\.conda\envs\py310\lib\site-packages\akshare\index\index_cons.py:109: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  [temp_df, pd.read_html(r.text, header=1)[3]], ignore_index=True
c:\Users\huzhe\.conda\envs\py310\lib\site-packages\akshare\index\index_cons.py:109: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  [temp_df, pd.read_html(r.text, header=1)[3]], ignore_index=True
c:\Users\huzhe\.conda\envs\py310\lib\site-packages\akshare\index\index_cons.py:109: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  [temp_df, pd.read_html(r.text, header=1)[3]], ignore_index=True
c:\Users\huzhe\.conda\envs\py310\lib\site-packages\akshare\index\index_cons.py:109: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  [temp_df, pd.read_html(r.text, header=1)[3]], ignore_index=True
c:\Users\huzhe\.conda\envs\py310\lib\site-packages\akshare\index\index_cons.py:109: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  [temp_df, pd.read_html(r.text, header=1)[3]], ignore_index=True
c:\Users\huzhe\.conda\envs\py310\lib\site-packages\akshare\index\index_cons.py:109: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  [temp_df, pd.read_html(r.text, header=1)[3]], ignore_index=True

       品种代码  品种名称        纳入日期
0    000983  山西焦煤  2023-06-12
1    600732  爱旭股份  2023-06-12
2    601872  招商轮船  2023-06-12
3    600754  锦江酒店  2023-06-12
4    000617  中油资本  2023-06-12
..      ...   ...         ...
295  000157  中联重科  2005-04-08
296  000069  华侨城A  2005-04-08
297  000063  中兴通讯  2005-04-08
298  000001  深发展A  2005-04-08
299  000002   万科A  2005-04-08

[300 rows x 3 columns]

In [6]:
# ak.stock_zh_a_hist接口用来获取历史行情，我们获取一下2015年到现在的行情，使用前复权，
# 调用成功后接口会返回一个包含股票历史行情的pandas对象，而pandas有个to_csv的接口可以把数据保存成csv文件
import akshare as ak
symbol_list=index_stock_cons_df['品种代码'].tolist()
for symbol in symbol_list:
    history_data=ak.stock_zh_a_hist(symbol=symbol, start_date="20150101",
                              end_date="20220330", adjust="qfq")
    history_data.to_csv('./data/'+symbol+".csv")
    print('saved '+symbol)

saved 000983
saved 600732
saved 601872
saved 600754
saved 000617
saved 688223
saved 601699
saved 600875
saved 601607
saved 601689
saved 000733
saved 688187
saved 600674
saved 002180
saved 600803
saved 300769
saved 600884
saved 605117
saved 600233
saved 601615
saved 002756
saved 600039
saved 688303
saved 000723
saved 601117
saved 300919
saved 001289
saved 300751
saved 603185
saved 002648
saved 300979
saved 000408
saved 600089
saved 002920
saved 603290
saved 300661
saved 300496
saved 300957
saved 002074
saved 600460
saved 603185
saved 002648
saved 688005
saved 000408
saved 000792
saved 300979
saved 600188
saved 300751
saved 300223
saved 600460
saved 001289
saved 300999
saved 601865
saved 603260
saved 002064
saved 601898
saved 002459
saved 002466
saved 300316
saved 300750
saved 000301
saved 688561
saved 688981
saved 300896
saved 603486
saved 002709
saved 605499
saved 300782
saved 601728
saved 300759
saved 601868
saved 300760
saved 688599
saved 600905
saved 601995
saved 601799
saved 603659
saved 688111
saved 688126
saved 600426
saved 601995
saved 601799
saved 600426
saved 600132
saved 300450
saved 300274
saved 000800
saved 002414
saved 600600
saved 688012
saved 603195
saved 002049
saved 600150
saved 600763
saved 603392
saved 688036
saved 600584
saved 600845
saved 002812
saved 600918
saved 002821
saved 688008
saved 000977
saved 300601
saved 601816
saved 603369
saved 600745
saved 601100
saved 000708
saved 002129
saved 002371
saved 003816
saved 300014
saved 300628
saved 601658
saved 002841
saved 002916
saved 300347
saved 600183
saved 600989
saved 601236
saved 601698
saved 603501
saved 603899
saved 000596
saved 002410
saved 002938
saved 300413
saved 300498
saved 601319
saved 603019
saved 002001
saved 601138
saved 002311
saved 600760
saved 601066
saved 300142
saved 002271
saved 603259
saved 002120
saved 603986
saved 002179
saved 000661
saved 002050
saved 300433
saved 002493
saved 300408
saved 000786
saved 601808
saved 600176
saved 600438
saved 600809
saved 601360
saved 600025
saved 600346
saved 603288
saved 601238
saved 601838
saved 601878
saved 300122
saved 603799
saved 600011
saved 603833
saved 002460
saved 601878
saved 300122
saved 300015
saved 002352
saved 002555
saved 600436
saved 600919
saved 600926
saved 601229
saved 601881
saved 002714
saved 300033
saved 601155
saved 601877
saved 000938
saved 002027
saved 600061
saved 600606
saved 001979
saved 601211
saved 601985
saved 002736
saved 300059
saved 600958
saved 601021
saved 601788
saved 601919
saved 000166
saved 600570
saved 300124
saved 601216
saved 601225
saved 002252
saved 002475
saved 600018
saved 002230
saved 000333
saved 000963
saved 600332
saved 603993
saved 002236
saved 600886
saved 601800
saved 000725
saved 002241
saved 601336
saved 601633
saved 601669
saved 601901
saved 002594
saved 601377
saved 000776
saved 002415
saved 600115
saved 600276
saved 600406
saved 600887
saved 600893
saved 601818
saved 601288
saved 002304
saved 600999
saved 601688
saved 601888
saved 601989
saved 002007
saved 601618
saved 601668
saved 601766
saved 000100
saved 600588
saved 601186
saved 601899
saved 002202
saved 601390
saved 601601
saved 601939
saved 000338
saved 000895
saved 002142
saved 600111
saved 601009
saved 601169
saved 601857
saved 601088
saved 600837
saved 000876
saved 601328
saved 601998
saved 601600
saved 601318
saved 601166
saved 601628
saved 600547
saved 601111
saved 600048
saved 601398
saved 601006
saved 601988
saved 600383
saved 000768
saved 000538
saved 600741
saved 600690
saved 600660
saved 600585
saved 600050
saved 000858
saved 000625
saved 000651
saved 000568
saved 000425
saved 000157
saved 000069
saved 000063
saved 000001
saved 600010
saved 600015
saved 600016
saved 600019
saved 600028
saved 600029
saved 600030
saved 600031
saved 600036
saved 600050
saved 000858
saved 000625
saved 000651
saved 000568
saved 000425
saved 000157
saved 000069
saved 000063
saved 000001
saved 000002

In [10]:
import pandas as pd
# 用read_csv读进来，并将第一列设为索引
df=pd.read_csv('./data/000001.csv',index_col=0)
df

,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,2015-01-05,9.51,9.53,9.71,9.24,2860436,4.565388e+09,5.00,1.38,0.13,2.91
1,2015-01-06,9.41,9.36,9.78,9.20,2166421,3.453446e+09,6.09,-1.78,-0.17,2.20
2,2015-01-07,9.21,9.15,9.39,9.03,1700121,2.634796e+09,3.85,-2.24,-0.21,1.73
3,2015-01-08,9.17,8.79,9.21,8.75,1407714,2.128003e+09,5.03,-3.93,-0.36,1.43
4,2015-01-09,8.75,8.87,9.42,8.62,2508500,3.835378e+09,9.10,0.91,0.08,2.55
...,...,...,...,...,...,...,...,...,...,...,...
1757,2022-03-24,14.41,14.69,14.80,14.30,1002360,1.518870e+09,3.45,1.38,0.20,0.52
1758,2022-03-25,14.64,14.47,14.74,14.31,742933,1.116355e+09,2.93,-1.50,-0.22,0.38
1759,2022-03-28,14.29,14.34,14.54,14.12,727137,1.078327e+09,2.90,-0.90,-0.13,0.37
1760,2022-03-29,14.37,14.17,14.44,14.09,615643,9.091696e+08,2.44,-1.19,-0.17,0.32
1761,2022-03-30,14.35,14.70,14.76,14.25,1236792,1.859617e+09,3.60,3.74,0.53,0.64

In [11]:
# 我们使用pandas的rename方法给这些列挨个改个名
df.rename(columns={'日期':'date', '开盘':'open', '收盘':'close', 
                   '最高':'high', '最低':'low', '成交量':'volume',
                   '成交额':'amount', '振幅':'swing', '涨跌幅':'chg_pct',
                   '涨跌额':'chg_amount', '换手率':'turnover',
                  }, inplace = True)
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
df=df.set_index('date')
df

,open,close,high,low,volume,amount,swing,chg_pct,chg_amount,turnover
date,,,,,,,,,,
2015-01-05,9.51,9.53,9.71,9.24,2860436,4.565388e+09,5.00,1.38,0.13,2.91
2015-01-06,9.41,9.36,9.78,9.20,2166421,3.453446e+09,6.09,-1.78,-0.17,2.20
2015-01-07,9.21,9.15,9.39,9.03,1700121,2.634796e+09,3.85,-2.24,-0.21,1.73
2015-01-08,9.17,8.79,9.21,8.75,1407714,2.128003e+09,5.03,-3.93,-0.36,1.43
2015-01-09,8.75,8.87,9.42,8.62,2508500,3.835378e+09,9.10,0.91,0.08,2.55
...,...,...,...,...,...,...,...,...,...,...
2022-03-24,14.41,14.69,14.80,14.30,1002360,1.518870e+09,3.45,1.38,0.20,0.52
2022-03-25,14.64,14.47,14.74,14.31,742933,1.116355e+09,2.93,-1.50,-0.22,0.38
2022-03-28,14.29,14.34,14.54,14.12,727137,1.078327e+09,2.90,-0.90,-0.13,0.37
2022-03-29,14.37,14.17,14.44,14.09,615643,9.091696e+08,2.44,-1.19,-0.17,0.32
2022-03-30,14.35,14.70,14.76,14.25,1236792,1.859617e+09,3.60,3.74,0.53,0.64

In [19]:
import backtrader as bt
import pandas as pd

class TestStrategy(bt.Strategy):
    def next(self):
        today=self.datas[0].datetime.date()
        for data in self.datas:
            symbol=data._name
            close=data.close[0]
            print("今天是："+str(today)+"，股票"+symbol
              +"，收盘价是："+str(close))

cerebro = bt.Cerebro()


symbol_list=index_stock_cons_df['品种代码'].tolist()
print('symbol_list:{}'.format(symbol_list))

for symbol in symbol_list[:10]:
    df=pd.read_csv('./data/'+symbol+'.csv',index_col=0)
    df.rename(columns={'日期':'date', '开盘':'open', '收盘':'close', 
                       '最高':'high', '最低':'low', '成交量':'volume',
                       '成交额':'amount', '振幅':'swing', '涨跌幅':'chg_pct',
                       '涨跌额':'chg_amount', '换手率':'turnover',
                      }, inplace = True)
    df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
    df=df.set_index('date') 
    data = bt.feeds.PandasData(dataname=df)
    cerebro.adddata(data,name=symbol)

# TestStrategy只是打印收盘价而已
cerebro.addstrategy(TestStrategy)
results = cerebro.run()

symbol_list:['000983', '600732', '601872', '600754', '000617', '688223', '601699', '600875', '601607', '601689', '000733', '688187', '600674', '002180', '600803', '300769', '600884', '605117', '600233', '601615', '002756', '600039', '688303', '000723', '601117', '300919', '001289', '300751', '603185', '002648', '300979', '000408', '600089', '002920', '603290', '300661', '300496', '300957', '002074', '600460', '603185', '002648', '688005', '000408', '000792', '300979', '600188', '300751', '300223', '600460', '001289', '300999', '601865', '603260', '002064', '601898', '002459', '002466', '300316', '300750', '000301', '688561', '688981', '300896', '603486', '002709', '605499', '300782', '601728', '300759', '601868', '300760', '688599', '600905', '601995', '601799', '603659', '688111', '688126', '600426', '601995', '601799', '600426', '600132', '300450', '300274', '000800', '002414', '600600', '688012', '603195', '002049', '600150', '600763', '603392', '688036', '600584', '600845', '002812', '600918', '002821', '688008', '000977', '300601', '601816', '603369', '600745', '601100', '000708', '002129', '002371', '003816', '300014', '300628', '601658', '002841', '002916', '300347', '600183', '600989', '601236', '601698', '603501', '603899', '000596', '002410', '002938', '300413', '300498', '601319', '603019', '002001', '601138', '002311', '600760', '601066', '300142', '002271', '603259', '002120', '603986', '002179', '000661', '002050', '300433', '002493', '300408', '000786', '601808', '600176', '600438', '600809', '601360', '600025', '600346', '603288', '601238', '601838', '601878', '300122', '603799', '600011', '603833', '002460', '601878', '300122', '300015', '002352', '002555', '600436', '600919', '600926', '601229', '601881', '002714', '300033', '601155', '601877', '000938', '002027', '600061', '600606', '001979', '601211', '601985', '002736', '300059', '600958', '601021', '601788', '601919', '000166', '600570', '300124', '601216', '601225', '002252', '002475', '600018', '002230', '000333', '000963', '600332', '603993', '002236', '600886', '601800', '000725', '002241', '601336', '601633', '601669', '601901', '002594', '601377', '000776', '002415', '600115', '600276', '600406', '600887', '600893', '601818', '601288', '002304', '600999', '601688', '601888', '601989', '002007', '601618', '601668', '601766', '000100', '600588', '601186', '601899', '002202', '601390', '601601', '601939', '000338', '000895', '002142', '600111', '601009', '601169', '601857', '601088', '600837', '000876', '601328', '601998', '601600', '601318', '601166', '601628', '600547', '601111', '600048', '601398', '601006', '601988', '600383', '000768', '000538', '600741', '600690', '600660', '600585', '600050', '000858', '000625', '000651', '000568', '000425', '000157', '000069', '000063', '000001', '600010', '600015', '600016', '600019', '600028', '600029', '600030', '600031', '600036', '600050', '000858', '000625', '000651', '000568', '000425', '000157', '000069', '000063', '000001', '000002']
今天是：2022-01-26，股票000983，收盘价是：6.52
今天是：2022-01-26，股票600732，收盘价是：13.37
今天是：2022-01-26，股票601872，收盘价是：3.65
今天是：2022-01-26，股票600754，收盘价是：58.17
今天是：2022-01-26，股票000617，收盘价是：4.85
今天是：2022-01-26，股票688223，收盘价是：10.44
今天是：2022-01-26，股票601699，收盘价是：9.19
今天是：2022-01-26，股票600875，收盘价是：17.66
今天是：2022-01-26，股票601607，收盘价是：18.05
今天是：2022-01-26，股票601689，收盘价是：57.34
今天是：2022-01-27，股票000983，收盘价是：6.35
今天是：2022-01-27，股票600732，收盘价是：13.28
今天是：2022-01-27，股票601872，收盘价是：3.57
今天是：2022-01-27，股票600754，收盘价是：56.88
今天是：2022-01-27，股票000617，收盘价是：4.78
今天是：2022-01-27，股票688223，收盘价是：10.06
今天是：2022-01-27，股票601699，收盘价是：9.06
今天是：2022-01-27，股票600875，收盘价是：17.11
今天是：2022-01-27，股票601607，收盘价是：17.9
今天是：2022-01-27，股票601689，收盘价是：55.27
今天是：2022-01-28，股票000983，收盘价是：5.75
今天是：2022-01-28，股票600732，收盘价是：12.78
今天是：2022-01-28，股票601872，收盘价是：3.58
今天是：2022-01-28，股票600754，收盘价是：56.13
今天是：2022-01-28，股票000617，收盘价是：4.79
今天是：2022-01-28，股票688223，收盘价是：10.4
今天是：2022-01-28，股票601699，收盘价是：8.57
今天是：2022-01-28，股票600875，收盘价是：16.59
今天是：2022-01-28，股票601607，收盘价是：17.85
今天是：2022-01-28，股票601689，收盘价是：53.26
今天是：2022-02-07，股票000983，收盘价是：6.11
今天是：2022-02-07，股票600732，收盘价是：13.04
今天是：2022-02-07，股票601872，收盘价是：3.79
今天是：2022-02-07，股票600754，收盘价是：54.82
今天是：2022-02-07，股票000617，收盘价是：4.91
今天是：2022-02-07，股票688223，收盘价是：10.54
今天是：2022-02-07，股票601699，收盘价是：8.62
今天是：2022-02-07，股票600875，收盘价是：16.97
今天是：2022-02-07，股票601607，收盘价是：18.2
今天是：2022-02-07，股票601689，收盘价是：54.55
今天是：2022-02-08，股票000983，收盘价是：6.81
今天是：2022-02-08，股票600732，收盘价是：12.34
今天是：2022-02-08，股票601872，收盘价是：3.98
今天是：2022-02-08，股票600754，收盘价是：57.99
今天是：2022-02-08，股票000617，收盘价是：5.12
今天是：2022-02-08，股票688223，收盘价是：10.21
今天是：2022-02-08，股票601699，收盘价是：9.49
今天是：2022-02-08，股票600875，收盘价是：17.19
今天是：2022-02-08，股票601607，收盘价是：18.45
今天是：2022-02-08，股票601689，收盘价是：51.81
今天是：2022-02-09，股票000983，收盘价是：6.9
今天是：2022-02-09，股票600732，收盘价是：12.76
今天是：2022-02-09，股票601872，收盘价是：3.98
今天是：2022-02-09，股票600754，收盘价是：59.89
今天是：2022-02-09，股票000617，收盘价是：5.15
今天是：2022-02-09，股票688223，收盘价是：10.95
今天是：2022-02-09，股票601699，收盘价是：9.05
今天是：2022-02-09，股票600875，收盘价是：17.38
今天是：2022-02-09，股票601607，收盘价是：18.53
今天是：2022-02-09，股票601689，收盘价是：54.63
今天是：2022-02-10，股票000983，收盘价是：7.11
今天是：2022-02-10，股票600732，收盘价是：11.79
今天是：2022-02-10，股票601872，收盘价是：4.03
今天是：2022-02-10，股票600754，收盘价是：61.0
今天是：2022-02-10，股票000617，收盘价是：5.13
今天是：2022-02-10，股票688223，收盘价是：9.85
今天是：2022-02-10，股票601699，收盘价是：9.25
今天是：2022-02-10，股票600875，收盘价是：16.9
今天是：2022-02-10，股票601607，收盘价是：18.51
今天是：2022-02-10，股票601689，收盘价是：52.69
今天是：2022-02-11，股票000983，收盘价是：7.36
今天是：2022-02-11，股票600732，收盘价是：11.71
今天是：2022-02-11，股票601872，收盘价是：4.06
今天是：2022-02-11，股票600754，收盘价是：60.54
今天是：2022-02-11，股票000617，收盘价是：5.01
今天是：2022-02-11，股票688223，收盘价是：9.3
今天是：2022-02-11，股票601699，收盘价是：9.47
今天是：2022-02-11，股票600875，收盘价是：15.99
今天是：2022-02-11，股票601607，收盘价是：18.24
今天是：2022-02-11，股票601689，收盘价是：50.26
今天是：2022-02-14，股票000983，收盘价是：7.21
今天是：2022-02-14，股票600732，收盘价是：11.65
今天是：2022-02-14，股票601872，收盘价是：3.99
今天是：2022-02-14，股票600754，收盘价是：60.17
今天是：2022-02-14，股票000617，收盘价是：4.94
今天是：2022-02-14，股票688223，收盘价是：9.31
今天是：2022-02-14，股票601699，收盘价是：9.55
今天是：2022-02-14，股票600875，收盘价是：15.43
今天是：2022-02-14，股票601607，收盘价是：17.97
今天是：2022-02-14，股票601689，收盘价是：51.06
今天是：2022-02-15，股票000983，收盘价是：7.05
今天是：2022-02-15，股票600732，收盘价是：12.24
今天是：2022-02-15，股票601872，收盘价是：3.94
今天是：2022-02-15，股票600754，收盘价是：59.6
今天是：2022-02-15，股票000617，收盘价是：4.91
今天是：2022-02-15，股票688223，收盘价是：9.88
今天是：2022-02-15，股票601699，收盘价是：9.06
今天是：2022-02-15，股票600875，收盘价是：15.7
今天是：2022-02-15，股票601607，收盘价是：18.02
今天是：2022-02-15，股票601689，收盘价是：53.62
今天是：2022-02-16，股票000983，收盘价是：7.06
今天是：2022-02-16，股票600732，收盘价是：12.09
今天是：2022-02-16，股票601872，收盘价是：3.95
今天是：2022-02-16，股票600754，收盘价是：59.27
今天是：2022-02-16，股票000617，收盘价是：4.93
今天是：2022-02-16，股票688223，收盘价是：10.31
今天是：2022-02-16，股票601699，收盘价是：9.2
今天是：2022-02-16，股票600875，收盘价是：15.65
今天是：2022-02-16，股票601607，收盘价是：18.07
今天是：2022-02-16，股票601689，收盘价是：53.61
今天是：2022-02-17，股票000983，收盘价是：7.27
今天是：2022-02-17，股票600732，收盘价是：12.29
今天是：2022-02-17，股票601872，收盘价是：3.88
今天是：2022-02-17，股票600754，收盘价是：58.16
今天是：2022-02-17，股票000617，收盘价是：4.9
今天是：2022-02-17，股票688223，收盘价是：10.41
今天是：2022-02-17，股票601699，收盘价是：9.34
今天是：2022-02-17，股票600875，收盘价是：15.61
今天是：2022-02-17，股票601607，收盘价是：17.86
今天是：2022-02-17，股票601689，收盘价是：55.05
今天是：2022-02-18，股票000983，收盘价是：8.15
今天是：2022-02-18，股票600732，收盘价是：12.29
今天是：2022-02-18，股票601872，收盘价是：4.15
今天是：2022-02-18，股票600754，收盘价是：59.19
今天是：2022-02-18，股票000617，收盘价是：4.95
今天是：2022-02-18，股票688223，收盘价是：10.41
今天是：2022-02-18，股票601699，收盘价是：10.01
今天是：2022-02-18，股票600875，收盘价是：15.45
今天是：2022-02-18，股票601607，收盘价是：17.96
今天是：2022-02-18，股票601689，收盘价是：53.71
今天是：2022-02-21，股票000983，收盘价是：8.99
今天是：2022-02-21，股票600732，收盘价是：12.37
今天是：2022-02-21，股票601872，收盘价是：4.19
今天是：2022-02-21，股票600754，收盘价是：59.74
今天是：2022-02-21，股票000617，收盘价是：4.96
今天是：2022-02-21，股票688223，收盘价是：11.27
今天是：2022-02-21，股票601699，收盘价是：11.13
今天是：2022-02-21，股票600875，收盘价是：15.45
今天是：2022-02-21，股票601607，收盘价是：18.18
今天是：2022-02-21，股票601689，收盘价是：53.83
今天是：2022-02-22，股票000983，收盘价是：9.06
今天是：2022-02-22，股票600732，收盘价是：12.63
今天是：2022-02-22，股票601872，收盘价是：4.21
今天是：2022-02-22，股票600754，收盘价是：56.99
今天是：2022-02-22，股票000617，收盘价是：4.9
今天是：2022-02-22，股票688223，收盘价是：11.54
今天是：2022-02-22，股票601699，收盘价是：10.84
今天是：2022-02-22，股票600875，收盘价是：15.05
今天是：2022-02-22，股票601607，收盘价是：17.85
今天是：2022-02-22，股票601689，收盘价是：54.56
今天是：2022-02-23，股票000983，收盘价是：9.07
今天是：2022-02-23，股票600732，收盘价是：13.52
今天是：2022-02-23，股票601872，收盘价是：4.31
今天是：2022-02-23，股票600754，收盘价是：56.07
今天是：2022-02-23，股票000617，收盘价是：4.95
今天是：2022-02-23，股票688223，收盘价是：11.32
今天是：2022-02-23，股票601699，收盘价是：10.71
今天是：2022-02-23，股票600875，收盘价是：15.66
今天是：2022-02-23，股票601607，收盘价是：17.88
今天是：2022-02-23，股票601689，收盘价是：58.06
今天是：2022-02-24，股票000983，收盘价是：8.77
今天是：2022-02-24，股票600732，收盘价是：13.49
今天是：2022-02-24，股票601872，收盘价是：4.28
今天是：2022-02-24，股票600754，收盘价是：55.84
今天是：2022-02-24，股票000617，收盘价是：4.83
今天是：2022-02-24，股票688223，收盘价是：11.53
今天是：2022-02-24，股票601699，收盘价是：10.27
今天是：2022-02-24，股票600875，收盘价是：15.46
今天是：2022-02-24，股票601607，收盘价是：17.52
今天是：2022-02-24，股票601689，收盘价是：57.48
今天是：2022-02-25，股票000983，收盘价是：8.23
今天是：2022-02-25，股票600732，收盘价是：13.72
今天是：2022-02-25，股票601872，收盘价是：4.2
今天是：2022-02-25，股票600754，收盘价是：55.88
今天是：2022-02-25，股票000617，收盘价是：4.87
今天是：2022-02-25，股票688223，收盘价是：11.48
今天是：2022-02-25，股票601699，收盘价是：9.7
今天是：2022-02-25，股票600875，收盘价是：15.83
今天是：2022-02-25，股票601607，收盘价是：17.6
今天是：2022-02-25，股票601689，收盘价是：58.54
今天是：2022-02-28，股票000983，收盘价是：8.58
今天是：2022-02-28，股票600732，收盘价是：14.06
今天是：2022-02-28，股票601872，收盘价是：4.29
今天是：2022-02-28，股票600754，收盘价是：56.08
今天是：2022-02-28，股票000617，收盘价是：5.38
今天是：2022-02-28，股票688223，收盘价是：12.39
今天是：2022-02-28，股票601699，收盘价是：10.4
今天是：2022-02-28，股票600875，收盘价是：15.7
今天是：2022-02-28，股票601607，收盘价是：17.65
今天是：2022-02-28，股票601689，收盘价是：59.44
今天是：2022-03-01，股票000983，收盘价是：8.8
今天是：2022-03-01，股票600732，收盘价是：13.97
今天是：2022-03-01，股票601872，收盘价是：4.19
今天是：2022-03-01，股票600754，收盘价是：56.09
今天是：2022-03-01，股票000617，收盘价是：5.23
今天是：2022-03-01，股票688223，收盘价是：12.62
今天是：2022-03-01，股票601699，收盘价是：11.03
今天是：2022-03-01，股票600875，收盘价是：15.75
今天是：2022-03-01，股票601607，收盘价是：17.58
今天是：2022-03-01，股票601689，收盘价是：59.79
今天是：2022-03-02，股票000983，收盘价是：9.0
今天是：2022-03-02，股票600732，收盘价是：13.99
今天是：2022-03-02，股票601872，收盘价是：4.29
今天是：2022-03-02，股票600754，收盘价是：56.32
今天是：2022-03-02，股票000617，收盘价是：5.34
今天是：2022-03-02，股票688223，收盘价是：12.75
今天是：2022-03-02，股票601699，收盘价是：11.55
今天是：2022-03-02，股票600875，收盘价是：15.8
今天是：2022-03-02，股票601607，收盘价是：17.81
今天是：2022-03-02，股票601689，收盘价是：58.59
今天是：2022-03-03，股票000983，收盘价是：9.35
今天是：2022-03-03，股票600732，收盘价是：13.11
今天是：2022-03-03，股票601872，收盘价是：4.45
今天是：2022-03-03，股票600754，收盘价是：59.26
今天是：2022-03-03，股票000617，收盘价是：5.52
今天是：2022-03-03，股票688223，收盘价是：12.19
今天是：2022-03-03，股票601699，收盘价是：12.13
今天是：2022-03-03，股票600875，收盘价是：15.72
今天是：2022-03-03，股票601607，收盘价是：18.0
今天是：2022-03-03，股票601689，收盘价是：53.78
今天是：2022-03-04，股票000983，收盘价是：9.47
今天是：2022-03-04，股票600732，收盘价是：13.33
今天是：2022-03-04，股票601872，收盘价是：4.27
今天是：2022-03-04，股票600754，收盘价是：59.56
今天是：2022-03-04，股票000617，收盘价是：5.24
今天是：2022-03-04，股票688223，收盘价是：12.22
今天是：2022-03-04，股票601699，收盘价是：12.32
今天是：2022-03-04，股票600875，收盘价是：15.31
今天是：2022-03-04，股票601607，收盘价是：18.12
今天是：2022-03-04，股票601689，收盘价是：52.11
今天是：2022-03-07，股票000983，收盘价是：10.02
今天是：2022-03-07，股票600732，收盘价是：13.04
今天是：2022-03-07，股票601872，收盘价是：4.21
今天是：2022-03-07，股票600754，收盘价是：55.83
今天是：2022-03-07，股票000617，收盘价是：5.22
今天是：2022-03-07，股票688223，收盘价是：12.31
今天是：2022-03-07，股票601699，收盘价是：12.71
今天是：2022-03-07，股票600875，收盘价是：14.92
今天是：2022-03-07，股票601607，收盘价是：18.27
今天是：2022-03-07，股票601689，收盘价是：50.11
今天是：2022-03-08，股票000983，收盘价是：9.04
今天是：2022-03-08，股票600732，收盘价是：12.96
今天是：2022-03-08，股票601872，收盘价是：4.1
今天是：2022-03-08，股票600754，收盘价是：52.69
今天是：2022-03-08，股票000617，收盘价是：5.0
今天是：2022-03-08，股票688223，收盘价是：12.41
今天是：2022-03-08，股票601699，收盘价是：11.96
今天是：2022-03-08，股票600875，收盘价是：14.2
今天是：2022-03-08，股票601607，收盘价是：17.52
今天是：2022-03-08，股票601689，收盘价是：50.84
今天是：2022-03-09，股票000983，收盘价是：9.29
今天是：2022-03-09，股票600732，收盘价是：13.02
今天是：2022-03-09，股票601872，收盘价是：4.02
今天是：2022-03-09，股票600754，收盘价是：50.8
今天是：2022-03-09，股票000617，收盘价是：4.92
今天是：2022-03-09，股票688223，收盘价是：12.09
今天是：2022-03-09，股票601699，收盘价是：12.86
今天是：2022-03-09，股票600875，收盘价是：14.31
今天是：2022-03-09，股票601607，收盘价是：16.87
今天是：2022-03-09，股票601689，收盘价是：52.95
今天是：2022-03-10，股票000983，收盘价是：9.23
今天是：2022-03-10，股票600732，收盘价是：13.11
今天是：2022-03-10，股票601872，收盘价是：3.94
今天是：2022-03-10，股票600754，收盘价是：50.61
今天是：2022-03-10，股票000617，收盘价是：5.02
今天是：2022-03-10，股票688223，收盘价是：12.79
今天是：2022-03-10，股票601699，收盘价是：13.13
今天是：2022-03-10，股票600875，收盘价是：14.74
今天是：2022-03-10，股票601607，收盘价是：18.06
今天是：2022-03-10，股票601689，收盘价是：55.04
今天是：2022-03-11，股票000983，收盘价是：9.49
今天是：2022-03-11，股票600732，收盘价是：12.43
今天是：2022-03-11，股票601872，收盘价是：4.09
今天是：2022-03-11，股票600754，收盘价是：50.43
今天是：2022-03-11，股票000617，收盘价是：5.07
今天是：2022-03-11，股票688223，收盘价是：12.29
今天是：2022-03-11，股票601699，收盘价是：13.48
今天是：2022-03-11，股票600875，收盘价是：14.57
今天是：2022-03-11，股票601607，收盘价是：18.3
今天是：2022-03-11，股票601689，收盘价是：54.06
今天是：2022-03-14，股票000983，收盘价是：9.1
今天是：2022-03-14，股票600732，收盘价是：11.99
今天是：2022-03-14，股票601872，收盘价是：3.93
今天是：2022-03-14，股票600754，收盘价是：47.14
今天是：2022-03-14，股票000617，收盘价是：4.95
今天是：2022-03-14，股票688223，收盘价是：12.2
今天是：2022-03-14，股票601699，收盘价是：12.44
今天是：2022-03-14，股票600875，收盘价是：13.95
今天是：2022-03-14，股票601607，收盘价是：18.27
今天是：2022-03-14，股票601689，收盘价是：51.79
今天是：2022-03-15，股票000983，收盘价是：7.99
今天是：2022-03-15，股票600732，收盘价是：11.16
今天是：2022-03-15，股票601872，收盘价是：3.52
今天是：2022-03-15，股票600754，收盘价是：45.61
今天是：2022-03-15，股票000617，收盘价是：4.61
今天是：2022-03-15，股票688223，收盘价是：12.46
今天是：2022-03-15，股票601699，收盘价是：10.84
今天是：2022-03-15，股票600875，收盘价是：12.88
今天是：2022-03-15，股票601607，收盘价是：17.22
今天是：2022-03-15，股票601689，收盘价是：53.32
今天是：2022-03-16，股票000983，收盘价是：8.16
今天是：2022-03-16，股票600732，收盘价是：11.75
今天是：2022-03-16，股票601872，收盘价是：3.63
今天是：2022-03-16，股票600754，收盘价是：49.19
今天是：2022-03-16，股票000617，收盘价是：4.75
今天是：2022-03-16，股票688223，收盘价是：12.21
今天是：2022-03-16，股票601699，收盘价是：10.86
今天是：2022-03-16，股票600875，收盘价是：13.43
今天是：2022-03-16，股票601607，收盘价是：17.55
今天是：2022-03-16，股票601689，收盘价是：58.73
今天是：2022-03-17，股票000983，收盘价是：8.48
今天是：2022-03-17，股票600732，收盘价是：11.68
今天是：2022-03-17，股票601872，收盘价是：3.59
今天是：2022-03-17，股票600754，收盘价是：51.07
今天是：2022-03-17，股票000617，收盘价是：4.75
今天是：2022-03-17，股票688223，收盘价是：11.73
今天是：2022-03-17，股票601699，收盘价是：11.38
今天是：2022-03-17，股票600875，收盘价是：13.59
今天是：2022-03-17，股票601607，收盘价是：19.41
今天是：2022-03-17，股票601689，收盘价是：58.75
今天是：2022-03-18，股票000983，收盘价是：9.07
今天是：2022-03-18，股票600732，收盘价是：11.59
今天是：2022-03-18，股票601872，收盘价是：3.6
今天是：2022-03-18，股票600754，收盘价是：51.7
今天是：2022-03-18，股票000617，收盘价是：4.84
今天是：2022-03-18，股票688223，收盘价是：11.72
今天是：2022-03-18，股票601699，收盘价是：12.48
今天是：2022-03-18，股票600875，收盘价是：13.79
今天是：2022-03-18，股票601607，收盘价是：21.45
今天是：2022-03-18，股票601689，收盘价是：57.57
今天是：2022-03-21，股票000983，收盘价是：9.69
今天是：2022-03-21，股票600732，收盘价是：11.77
今天是：2022-03-21，股票601872，收盘价是：3.57
今天是：2022-03-21，股票600754，收盘价是：51.01
今天是：2022-03-21，股票000617，收盘价是：4.8
今天是：2022-03-21，股票688223，收盘价是：12.28
今天是：2022-03-21，股票601699，收盘价是：12.88
今天是：2022-03-21，股票600875，收盘价是：13.72
今天是：2022-03-21，股票601607，收盘价是：23.7
今天是：2022-03-21，股票601689，收盘价是：57.7
今天是：2022-03-22，股票000983，收盘价是：10.73
今天是：2022-03-22，股票600732，收盘价是：11.52
今天是：2022-03-22，股票601872，收盘价是：3.62
今天是：2022-03-22，股票600754，收盘价是：50.25
今天是：2022-03-22，股票000617，收盘价是：4.89
今天是：2022-03-22，股票688223，收盘价是：12.16
今天是：2022-03-22，股票601699，收盘价是：13.58
今天是：2022-03-22，股票600875，收盘价是：13.67
今天是：2022-03-22，股票601607，收盘价是：23.91
今天是：2022-03-22，股票601689，收盘价是：58.17
今天是：2022-03-23，股票000983，收盘价是：10.51
今天是：2022-03-23，股票600732，收盘价是：11.74
今天是：2022-03-23，股票601872，收盘价是：3.56
今天是：2022-03-23，股票600754，收盘价是：50.49
今天是：2022-03-23，股票000617，收盘价是：4.85
今天是：2022-03-23，股票688223，收盘价是：12.46
今天是：2022-03-23，股票601699，收盘价是：13.32
今天是：2022-03-23，股票600875，收盘价是：14.17
今天是：2022-03-23，股票601607，收盘价是：22.97
今天是：2022-03-23，股票601689，收盘价是：57.62
今天是：2022-03-24，股票000983，收盘价是：10.77
今天是：2022-03-24，股票600732，收盘价是：11.43
今天是：2022-03-24，股票601872，收盘价是：3.51
今天是：2022-03-24，股票600754，收盘价是：49.29
今天是：2022-03-24，股票000617，收盘价是：4.76
今天是：2022-03-24，股票688223，收盘价是：12.08
今天是：2022-03-24，股票601699，收盘价是：13.3
今天是：2022-03-24，股票600875，收盘价是：13.82
今天是：2022-03-24，股票601607，收盘价是：25.37
今天是：2022-03-24，股票601689，收盘价是：57.02
今天是：2022-03-25，股票000983，收盘价是：10.78
今天是：2022-03-25，股票600732，收盘价是：11.04
今天是：2022-03-25，股票601872，收盘价是：3.54
今天是：2022-03-25，股票600754，收盘价是：48.03
今天是：2022-03-25，股票000617，收盘价是：4.76
今天是：2022-03-25，股票688223，收盘价是：11.45
今天是：2022-03-25，股票601699，收盘价是：12.75
今天是：2022-03-25，股票600875，收盘价是：13.43
今天是：2022-03-25，股票601607，收盘价是：24.27
今天是：2022-03-25，股票601689，收盘价是：54.64
今天是：2022-03-28，股票000983，收盘价是：10.67
今天是：2022-03-28，股票600732，收盘价是：10.64
今天是：2022-03-28，股票601872，收盘价是：3.92
今天是：2022-03-28，股票600754，收盘价是：48.03
今天是：2022-03-28，股票000617，收盘价是：4.85
今天是：2022-03-28，股票688223，收盘价是：11.45
今天是：2022-03-28，股票601699，收盘价是：12.91
今天是：2022-03-28，股票600875，收盘价是：13.25
今天是：2022-03-28，股票601607，收盘价是：23.39
今天是：2022-03-28，股票601689，收盘价是：54.16
今天是：2022-03-29，股票000983，收盘价是：10.86
今天是：2022-03-29，股票600732，收盘价是：10.33
今天是：2022-03-29，股票601872，收盘价是：4.34
今天是：2022-03-29，股票600754，收盘价是：49.08
今天是：2022-03-29，股票000617，收盘价是：4.81
今天是：2022-03-29，股票688223，收盘价是：11.3
今天是：2022-03-29，股票601699，收盘价是：13.23
今天是：2022-03-29，股票600875，收盘价是：13.02
今天是：2022-03-29，股票601607，收盘价是：23.39
今天是：2022-03-29，股票601689，收盘价是：54.58
今天是：2022-03-30，股票000983，收盘价是：10.1
今天是：2022-03-30，股票600732，收盘价是：10.82
今天是：2022-03-30，股票601872，收盘价是：4.36
今天是：2022-03-30，股票600754，收盘价是：50.11
今天是：2022-03-30，股票000617，收盘价是：4.86
今天是：2022-03-30，股票688223，收盘价是：12.09
今天是：2022-03-30，股票601699，收盘价是：12.71
今天是：2022-03-30，股票600875，收盘价是：13.57
今天是：2022-03-30，股票601607，收盘价是：23.31
今天是：2022-03-30，股票601689，收盘价是：57.8

In [24]:
import pandas as pd
import talib as ta
df=pd.read_csv('./data/000001.csv',index_col=0)
df.rename(columns={'日期':'date', '开盘':'open', '收盘':'close', 
                   '最高':'high', '最低':'low', '成交量':'volume',
                   '成交额':'amount', '振幅':'swing', '涨跌幅':'chg_pct',
                   '涨跌额':'chg_amount', '换手率':'turnover',
                  }, inplace = True)
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
df=df.set_index('date')

# 计算MACD
df['dif'], df['dea'], df['macd'] = ta.MACD(df.close, fastperiod=12, slowperiod=26, signalperiod=9)
df

,open,close,high,low,volume,amount,swing,chg_pct,chg_amount,turnover,dif,dea,macd
date,,,,,,,,,,,,,
2015-01-05,9.51,9.53,9.71,9.24,2860436,4.565388e+09,5.00,1.38,0.13,2.91,NaN,NaN,NaN
2015-01-06,9.41,9.36,9.78,9.20,2166421,3.453446e+09,6.09,-1.78,-0.17,2.20,NaN,NaN,NaN
2015-01-07,9.21,9.15,9.39,9.03,1700121,2.634796e+09,3.85,-2.24,-0.21,1.73,NaN,NaN,NaN
2015-01-08,9.17,8.79,9.21,8.75,1407714,2.128003e+09,5.03,-3.93,-0.36,1.43,NaN,NaN,NaN
2015-01-09,8.75,8.87,9.42,8.62,2508500,3.835378e+09,9.10,0.91,0.08,2.55,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-24,14.41,14.69,14.80,14.30,1002360,1.518870e+09,3.45,1.38,0.20,0.52,-0.343682,-0.477993,0.134311
2022-03-25,14.64,14.47,14.74,14.31,742933,1.116355e+09,2.93,-1.50,-0.22,0.38,-0.308374,-0.444069,0.135695
2022-03-28,14.29,14.34,14.54,14.12,727137,1.078327e+09,2.90,-0.90,-0.13,0.37,-0.287567,-0.412769,0.125201
2022-03-29,14.37,14.17,14.44,14.09,615643,9.091696e+08,2.44,-1.19,-0.17,0.32,-0.281550,-0.386525,0.104975
2022-03-30,14.35,14.70,14.76,14.25,1236792,1.859617e+09,3.60,3.74,0.53,0.64,-0.231348,-0.355490,0.124142

In [26]:
import pandas as pd

df_base=pd.read_csv('./data/000001.csv',index_col=0)
df_base.rename(columns={'日期':'date'}, inplace = True)
df_base['date'] = pd.to_datetime(df_base['date'], format='%Y-%m-%d')
df_base=df_base['date']


df=pd.read_csv('./data/605499.csv',index_col=0)
df.rename(columns={'日期':'date', '开盘':'open', '收盘':'close', 
                   '最高':'high', '最低':'low', '成交量':'volume',
                   '成交额':'amount', '振幅':'swing', '涨跌幅':'chg_pct',
                   '涨跌额':'chg_amount', '换手率':'turnover',
                  }, inplace = True)

df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
df=pd.merge(df_base,df,on=['date'],how='outer')
df

,date,open,close,high,low,volume,amount,swing,chg_pct,chg_amount,turnover
0,2015-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1757,2022-03-24,137.50,136.40,137.60,134.01,7589.0,105421161.0,2.59,-1.66,-2.30,1.90
1758,2022-03-25,137.15,130.44,137.15,128.50,13464.0,182664485.0,6.34,-4.37,-5.96,3.37
1759,2022-03-28,130.00,128.29,130.40,123.73,10782.0,140779560.0,5.11,-1.65,-2.15,2.69
1760,2022-03-29,128.20,126.73,130.26,126.25,6226.0,81915350.0,3.13,-1.22,-1.56,1.56
1761,2022-03-30,127.97,130.86,132.66,126.50,11589.0,154721122.0,4.86,3.26,4.13,2.90

In [25]:
import backtrader as bt
import pandas as pd
import math
import talib as ta
import numpy as np
from backtrader.feeds import PandasData
from datetime import datetime

class Addmoredata(PandasData):
    lines = ('dif','dea','macd',)
    params = (('dif',10),('dea',11),('macd',12),)

class TestStrategy(bt.Strategy):
    def __init__(self):
        df_base=pd.read_csv('./data/000001.csv',index_col=0)
        df_base.rename(columns={'日期':'date'}, inplace = True)
        df_base['date'] = pd.to_datetime(df_base['date'], format='%Y-%m-%d')
        df_base=df_base['date']
        self.df_base=df_base
        
    def next(self):   
        today=self.datas[0].datetime.date()
        for data in self.datas:
            symbol=data._name
            close=data.close[0]
            print("今天是："+str(today)+"，股票"+symbol
              +"，MACD是："+str(data.macd[0]))

cerebro = bt.Cerebro()

start=datetime.strptime('20150101', "%Y%m%d")
end=datetime.strptime('20220330', "%Y%m%d")

symbol_list=index_stock_cons_df['品种代码'].tolist()
for symbol in symbol_list[:10]:
    df=pd.read_csv('./data/'+symbol+'.csv',index_col=0)
    df.rename(columns={'日期':'date', '开盘':'open', '收盘':'close', 
                       '最高':'high', '最低':'low', '成交量':'volume',
                       '成交额':'amount', '振幅':'swing', '涨跌幅':'chg_pct',
                       '涨跌额':'chg_amount', '换手率':'turnover',
                      }, inplace = True)
    df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
    df=pd.merge(df_base,df,on=['date'],how='outer')
    df=df.set_index('date') 
    df['dif'], df['dea'], df['macd'] = ta.MACD(df.close, fastperiod=12, slowperiod=26, signalperiod=9)
    df=df.fillna(0)
    #print(df)
    #data = bt.feeds.PandasData(dataname=df)
    data=Addmoredata(dataname=df,fromdate=start,todate=end,sessionstart=start)
    cerebro.adddata(data,name=symbol)

cerebro.addstrategy(TestStrategy)
results = cerebro.run()

NameError: name 'df_base' is not defined